### PR TITLE
Ang profile and my itineraries functionality

### LINKED ISSUE #146: Registered users functionality view
This issue includes: 

- [ ] Profile view.
- [ ] Profile editing.
- [ ] My itineraries view.
- [ ] Allow creating an itinerary in "my itineraries".
- [ ] Allow deleting an owned itinerary in "my itineraries".
- [ ] Allow editing details of an owned itinerary in "my itineraries".
- [ ] Handle access to those pages (only "USER"s might be able to access to them).

### PR DESCRIPTION
**Pull request by LovetheFrogs**

### CODE REVIEW

**Review by AdayaUwU — CHANGES_REQUESTED** [review]
Can't accept pull request since we can't check if the services and models work without the classes that use them, also there are services missing that are necessary for this part, for example the services needed for my itineraries page. There is no point on making such an incomplete pull request.

**Comment by LovetheFrogs** [comment]
Moved changes from #156 here so it can all be tested. Could not check if image uploading fully works, as my browser is not allowing the app to open the file dialog to select an image, but it should work as expected, as the implementation is based on the others for image uploading

**Review by AdayaUwU — CHANGES_REQUESTED** [review]
Neither the itinerary or profile pictures are uploaded, the profile data takes way too long to load because you are not using the correct method, the links referencing the details page are wrong, and the itinerary data doesn't load on the editing itinerary page. Please check your work properly before making a pull request.

**Comment by LovetheFrogs** [comment]
Requesting review of new changes do to problems with database connection, as it doesn't seem to be working as intended on my end and it is making every request get back with a 500 error code as can be seen in screenshot below
image
Image shows one request as this is inside the /profile page, but you can get the hang of this behaviour

**Comment by LovetheFrogs** [comment]
> Requesting review of new changes do to problems with database connection, as it doesn't seem to be working as intended on my end and it is making every request get back with a 500 error code as can be seen in screenshot below image Image shows one request as this is inside the /profile page, but you can get the hang of this behaviour

Fixed, tested everything and it WAI

**Review by AdayaUwU — CHANGES_REQUESTED** [review]
Images are still not uploading and there is no pagination on my itineraries page, change that and create the pull request when it works.

**Review by AdayaUwU — CHANGES_REQUESTED** [review]
Itineraries privacy settings work wrong, the lock icon appears on the public ones and the checkbox to make them private makes them public and viceversa. 
Once again, please check properly that everything works before making the PR as I have been asking many times.

**Comment by AdayaUwU** [comment]
Also, please change all the href links to router links since the rest of the team is working on the changes that are in dev and we can't also fix your links. You can see the fix-navigation branch for reference.

**Pull request merged**
